# Generated by Django 5.1.3 on 2024-11-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.TextField(help_text='Enter the ingredients, seperated by commas', max_length=255)),
                ('cooking_time', models.IntegerField(help_text='Enter the cooking time in minutes')),
            ],
        ),
    ]
